# Funding Configuration

github: [your-username]
patreon: gasless-subscribe
open_collective: gasless-subscription-system
ko_fi: gasless_subscribe
custom: ['https://polygon.technology/grants', 'https://ethereum.foundation/grants']