name: Compile Contracts

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'contracts/**'
      - 'hardhat.config.js'
      - 'package.json'
  pull_request:
    branches: [ main ]
    paths:
      - 'contracts/**'
      - 'hardhat.config.js'
      - 'package.json'

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Compile contracts
      run: npx hardhat compile

    - name: Check for compilation warnings
      run: |
        if grep -q "Warning" artifacts/contracts/*.sol/*.json; then
          echo "⚠️ Compilation warnings found"
          exit 0
        else
          echo "✅ Clean compilation"
        fi

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: compiled-contracts
        path: |
          artifacts/
          typechain-types/
        retention-days: 7