name: Lint Code

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'sdk/**'
      - '*.js'
      - '*.ts'
  pull_request:
    branches: [ main ]
    paths:
      - 'sdk/**'
      - '*.js'
      - '*.ts'

jobs:
  lint-sdk:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Install SDK dependencies
      run: cd sdk && npm ci

    - name: Lint SDK
      run: cd sdk && npm run lint

    - name: Type check SDK
      run: cd sdk && npm run type-check

  lint-sdk-secondary:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install SDK dependencies
      run: cd sdk && npm ci

    - name: Lint SDK
      run: cd sdk && npm run lint

    - name: Type check SDK
      run: cd sdk && npm run type-check

    - name: Build SDK
      run: cd sdk && npm run build